// ============ Wallet Actions ============

export const WALLET_CREATE_PWD = "WALLET_CREATE_PWD";
export const WALLET_NEW_HD_ACCOUNT = "WALLET_NEW_HD_ACCOUNT";
export const WALLET_GET_CURRENT_ACCOUNT = "WALLET_GET_CURRENT_ACCOUNT";
export const WALLET_SET_UNLOCKED_STATUS = "WALLET_SET_UNLOCKED_STATUS";
export const WALLET_APP_SUBMIT_PWD = "WALLET_APP_SUBMIT_PWD";
export const WALLET_GET_ALL_ACCOUNT = "WALLET_GET_ALL_ACCOUNT";
export const WALLET_CREATE_HD_ACCOUNT = "WALLET_CREATE_HD_ACCOUNT";
export const WALLET_IMPORT_HD_ACCOUNT = "WALLET_IMPORT_HD_ACCOUNT";
export const WALLET_CHANGE_CURRENT_ACCOUNT = "WALLET_CHANGE_CURRENT_ACCOUNT";
export const WALLET_CHANGE_ACCOUNT_NAME = "WALLET_CHANGE_ACCOUNT_NAME";
export const WALLET_CHANGE_DELETE_ACCOUNT = "WALLET_CHANGE_DELETE_ACCOUNT";
export const WALLET_CHECKOUT_PASSWORD = "WALLET_CHECKOUT_PASSWORD";
export const WALLET_GET_MNE = "WALLET_GET_MNE";
export const WALLET_GET_PRIVATE_KEY = "WALLET_GET_PRIVATE_KEY";
export const WALLET_CHANGE_SEC_PASSWORD = "WALLET_CHANGE_SEC_PASSWORD";
export const WALLET_SEND_FIELDS_MESSAGE_TRANSACTION = "WALLET_SEND_FIELDS_MESSAGE_TRANSACTION";
export const WALLET_CHECK_TX_STATUS = "WALLET_CHECK_TX_STATUS";
export const WALLET_IMPORT_LEDGER = "WALLET_IMPORT_LEDGER";
export const WALLET_IMPORT_KEY_STORE = "WALLET_IMPORT_KEY_STORE";
export const WALLET_GET_CREATE_MNEMONIC = "WALLET_GET_CREATE_MNEMONIC";
export const WALLET_RESET_LAST_ACTIVE_TIME = "WALLET_RESET_LAST_ACTIVE_TIME";
export const WALLET_UPDATE_LOCK_TIME = "WALLET_UPDATE_LOCK_TIME";
export const WALLET_GET_LOCK_TIME = "WALLET_GET_LOCK_TIME";

// ============ Back to Popup Actions ============

export const FROM_BACK_TO_RECORD = "FROM_BACK_TO_RECORD";
export const TX_SUCCESS = "TX_SUCCESS";
export const SET_LOCK = "SET_LOCK";
export const LEDGER_CONNECTED_SUCCESSFULLY = "LEDGER_CONNECTED_SUCCESSFULLY";
export const WALLET_DELETE_WATCH_ACCOUNT = "WALLET_DELETE_WATCH_ACCOUNT";
export const RESET_WALLET = "RESET_WALLET";

// ============ Sign Actions ============

export const GET_SIGN_PARAMS_BY_ID = "GET_SIGN_PARAMS_BY_ID";
export const GET_SIGN_PARAMS = "GET_SIGN_PARAMS";
export const GET_APPROVE_PARAMS = "GET_APPROVE_PARAMS";

// ============ DApp Actions ============

export const DAPP_GET_CURRENT_ACCOUNT_CONNECT_STATUS = "DAPP_GET_CURRENT_ACCOUNT_CONNECT_STATUS";
export const DAPP_ACTION_SEND_TRANSACTION = "DAPP_ACTION_SEND_TRANSACTION";
export const DAPP_ACTION_SIGN_MESSAGE = "DAPP_ACTION_SIGN_MESSAGE";
export const DAPP_ACTION_GET_ACCOUNT = "DAPP_ACTION_GET_ACCOUNT";
export const DAPP_ACTION_CLOSE_WINDOW = "DAPP_ACTION_CLOSE_WINDOW";
export const DAPP_DISCONNECT_SITE = "DAPP_DISCONNECT_SITE";
export const DAPP_DELETE_ACCOUNT_CONNECT_HIS = "DAPP_DELETE_ACCOUNT_CONNECT_HIS";
export const DAPP_CHANGE_CONNECTING_ADDRESS = "DAPP_CHANGE_CONNECTING_ADDRESS";
export const DAPP_CLOSE_POPUP_WINDOW = "DAPP_CLOSE_POPUP_WINDOW";
export const DAPP_CHANGE_NETWORK = "DAPP_CHANGE_NETWORK";
export const DAPP_CONNECTION_LIST = "DAPP_CONNECTION_LIST";
export const DAPP_ACTION_SWITCH_CHAIN = "DAPP_ACTION_SWITCH_CHAIN";
export const DAPP_ACTION_CANCEL_ALL = "DAPP_ACTION_CANCEL_ALL";
export const DAPP_ACTION_CREATE_NULLIFIER = "DAPP_ACTION_CREATE_NULLIFIER";
export const DAPP_ACTION_STORE_CREDENTIAL = "DAPP_ACTION_STORE_CREDENTIAL";
export const DAPP_ACTION_REQUEST_PRESENTATION = "DAPP_ACTION_REQUEST_PRESENTATION";

// ============ QA Actions ============

export const QA_SIGN_TRANSACTION = "QA_SIGN_TRANSACTION";
export const GET_WALLET_LOCK_STATUS = "GET_WALLET_LOCK_STATUS";
export const GET_LEDGER_ACCOUNT_NUMBER = "GET_LEDGER_ACCOUNT_NUMBER";
export const WALLET_SEND_NULLIFIER = "WALLET_SEND_NULLIFIER";

// ============ Popup Actions ============

export const POPUP_ACTIONS = {
  INIT_APPROVE_LIST: "INIT_APPROVE_LIST",
  POPUP_NOTIFICATION: "POPUP_NOTIFICATION",
  GET_ALL_PENDING_ZK: "POPUP_GET_ALL_PENDING_ZK",
} as const;

// ============ Worker Actions ============

export const WORKER_ACTIONS = {
  BUILD_TOKEN_SEND: "WORKER_BUILD_TOKEN_SEND",
  APPROVE: "WORKER_APPROVE",
  SIGN_ZK: "WORKER_SIGN_ZK",
  SET_LOCK: "WORKER_SET_LOCK",
} as const;

// ============ Account Actions ============

export const ACCOUNT_ACTIONS = {
  REFRESH_CURRENT_ACCOUNT: "REFRESH_CURRENT_ACCOUNT",
} as const;

// ============ Credential Messages ============

export const CredentialMsg = {
  ID_LIST: "Credential_id_list",
  target_credential: "target_credential",
  remove_credential_detail: "remove_credential_detail",
  store_credential: "store_credential",
  get_credentials: "get_credentials",
} as const;

// ============ Multi-Wallet Message Types ============

export const WALLET_GET_KEYRINGS_LIST = "WALLET_GET_KEYRINGS_LIST";
export const WALLET_ADD_HD_KEYRING = "WALLET_ADD_HD_KEYRING";
export const WALLET_RENAME_KEYRING = "WALLET_RENAME_KEYRING";
export const WALLET_GET_KEYRING_MNEMONIC = "WALLET_GET_KEYRING_MNEMONIC";
export const WALLET_DELETE_KEYRING = "WALLET_DELETE_KEYRING";
export const WALLET_ADD_ACCOUNT_TO_KEYRING = "WALLET_ADD_ACCOUNT_TO_KEYRING";
export const WALLET_GET_VAULT_VERSION = "WALLET_GET_VAULT_VERSION";
export const WALLET_TRY_UPGRADE_VAULT = "WALLET_TRY_UPGRADE_VAULT";
